config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get "home/about" => "homes#about"

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
    get '/search' => 'searches#index'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } #今週
  scope :created_lastweek, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } # 前週

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end
#間違い
 # scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
 # scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
 # scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } #今週
 # scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } # 前週

#正解
	# scope :created_today, -> { where(created_at: Time.current.all_day) } # 今日
	# scope :created_yesterday, -> { where(created_at: Time.zone.yesterday.all_day) } # 昨日
	# scope :created_this_week, -> { where(created_at: Time.current.all_week) } # 今週
	# scope :created_last_week_ago, -> { where(created_at: Time.current.last_week.all_week) } # 先週

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    @users = User.all
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_back fallback_location: root_path, notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to books_path, notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
    <% book_comment_user = book_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
      		<%= attachment_image_tag book_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= book_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= book_comment.comment %></td>
    	<% if current_user == book_comment_user %>
      	<td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), remote: true, class: 'btn-sm btn-danger', method: :delete %></td>
    	<% end %>
    </tr>
  <% end %>
</table>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_graph.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        
        <td id="favorites_btn_<%= book.id %>">
          <%= render "favorites/favorite-btn", book: book %>
        </td>
        
        <td>コメント数: <%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_post-day.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">day</th>
      <th scope="col">本日</th>
      <th scope="col">前日</th>
      <th scope="col">前日比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"></th>
      <td>
         <%= book_today.count %>件
      </td>
      <td>
         <%= book_yesterday.count %>件
      </td>
      <td>
        <% if book_yesterday.count == 0 %>
          <%= (book_today.count * 100) %>%
        <% else %>
          <% @day_before = book_today.count / book_yesterday.count.to_f %>
          <%= (@day_before * 100).round %>%
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">week</th>
      <th scope="col">今週</th>
      <th scope="col">前週</th>
      <th scope="col">前週比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"></th>
      <td>
        <%= book_week.count %>件
      </td>
      <td>
        <%= book_lastweek.count %>件
      </td>
      <td>
        <% if book_lastweek.count == 0 %>
          <%= (book_week.count * 100) %>%
        <% else %>
          <% @week_before = book_week.count / book_lastweek.count.to_f %>
          <%= (@week_before * 100).round %>%
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
      

      
      
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>





      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <!--非同期-->
          <td id="favorites_btn_<%= @book.id %>">
            <%= render "favorites/favorite-btn", book: @book %>
            </td>
          <td>コメント数: <%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <div id="comment_<%= @book.id %>">
        <%= render 'books/comment', book: @book %>
      </div>
      <%= form_with model:[@book, @book_comment], remote: true, id: "comment" do |f| %>
        <%= f.text_area :comment, size:"90x5" %><br>
        <%= f.submit '送信' %>
      <% end %>
    </div>
  </div>
</div>